server {
    listen 80;
    client_max_body_size 100M;

    location /images/ {
        alias /srv/images/;
        expires 30d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://web:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
